import { createContext, useContext, useState } from "react";
import button from "../components/Button";
import Logo from '../images/teresaLogo.png';
import Logo_white from '../images/teresaLogoWhite.png';
import hero1 from '../images/hero3.webp';
import hero2 from '../images/hero2.webp';
import hero3 from '../images/hero1.webp';
import managment from '../images/managment.png';
import engineering from '../images/engineering.png';
import medical from '../images/medical.png';
import abroad from '../images/abroad.png';
import distance from '../images/distance.png';
//top schools
import auro from '../images/institutes/auro.png'
import gims from '../images/institutes/gims.png'
import iba from '../images/institutes/iba.jpg'
import iicmt from '../images/institutes/iicmt-featured.png'
import isbm from '../images/institutes/isbm.png'
import isbr from '../images/institutes/isbr.jpg'
import ISBS from '../images/institutes/ISBS-PAGE-featured.png'
import itm from '../images/institutes/itm.png'
import jagsom from '../images/institutes/jagsom.png'
import patil from '../images/institutes/patil.jpg'
import nbs from '../images/institutes/nbs.jpg'
import pgdm from '../images/institutes/pgdm.png'
import pgdm2 from '../images/institutes/pgdm2.png'
import pgmd from '../images/institutes/pgmd.png'
import rcm from '../images/institutes/rcm.jpg'
import sbs from '../images/institutes/sbs.jpg'

//testimonials
import at_1 from '../images/at_1.png'
import at_2 from '../images/at_2.jpg'
import at_3 from '../images/at_3.jpg'
import at_4 from '../images/at_4.jpg'
import at_5 from '../images/at_5.jpg'
import at_6 from '../images/at_6.jpg'

//icons
import {
  BsInstagram,
  BsFacebook,
  BsLinkedin,
  BsTwitter,
  BsYoutube,
  BsTelephoneFill,
  BsEnvelopeFill,
  BsGeoAltFill
} from "react-icons/bs";

const AppContext = createContext();

export const AppProvider = ({ children }) => {

  // static logo
  const logo = Logo;
  const Button = button;
  // static menus
  const menus = [
    { name: "Home", path: "/" },
    { name: "About Us", path: "/about" },
    { name: "Team", path: "/team" },
    { name: "Our Clients", path: "/clients" },
    { name: "Contact Us", path: "/contact" }
  ];
  // static footer data
  const footer = {
    logo: Logo_white,
    description: "Mother Teresa Educational Foundation, Ananthapuramu, Andhra Pradesh — empowering students with quality education and guidance.",

    leftLinks: [
      { name: "Home", path: "/" },
      { name: "About", path: "/about" },
      { name: "Team", path: "/team" },
      { name: "Careers", path: "/careers" },
      { name: "Contact", path: "/contact" }
    ],

    rightLinks: [
      { name: "Privacy Policy", path: "/" },
      { name: "Terms & Conditions", path: "/" },
      { name: "FAQ", path: "/" },
      { name: "Support", path: "/" }
    ]
  };
  // ---------- STATES + CITIES DATA ----------
  const indiaData = {

    Haryana: [
      "Faridabad",
      "Gurgaon",
      "Hisar",
      "Rohtak",
      "Panipat",
      "Karnal",
      "Sonipat",
      "Yamunanagar",
      "Panchkula",
      "Bhiwani",
      "Bahadurgarh",
      "Jind",
      "Sirsa",
      "Thanesar",
      "Kaithal",
      "Palwal",
      "Rewari",
      "Hansi",
      "Narnaul",
      "Fatehabad",
      "Gohana",
      "Tohana",
      "Narwana",
      "Mandi Dabwali",
      "Charkhi Dadri",
      "Shahbad",
      "Pehowa",
      "Samalkha",
      "Pinjore",
      "Ladwa",
      "Sohna",
      "Safidon",
      "Taraori",
      "Mahendragarh",
      "Ratia",
      "Rania",
      "Sarsod"
    ],
    "Tamil Nadu": [
      "Chennai",
      "Coimbatore",
      "Madurai",
      "Tiruchirappalli",
      "Salem",
      "Tirunelveli",
      "Tiruppur",
      "Ranipet",
      "Nagercoil",
      "Thanjavur",
      "Vellore",
      "Kancheepuram",
      "Erode",
      "Tiruvannamalai",
      "Pollachi",
      "Rajapalayam",
      "Sivakasi",
      "Pudukkottai",
      "Neyveli (TS)",
      "Nagapattinam",
      "Viluppuram",
      "Tiruchengode",
      "Vaniyambadi",
      "Theni Allinagaram",
      "Udhagamandalam",
      "Aruppukkottai",
      "Paramakudi",
      "Arakkonam",
      "Virudhachalam",
      "Srivilliputhur",
      "Tindivanam",
      "Virudhunagar",
      "Karur",
      "Valparai",
      "Sankarankovil",
      "Tenkasi",
      "Palani",
      "Pattukkottai",
      "Tirupathur",
      "Ramanathapuram",
      "Udumalaipettai",
      "Gobichettipalayam",
      "Thiruvarur",
      "Thiruvallur",
      "Panruti",
      "Namakkal",
      "Thirumangalam",
      "Vikramasingapuram",
      "Nellikuppam",
      "Rasipuram",
      "Tiruttani",
      "Nandivaram-Guduvancheri",
      "Periyakulam",
      "Pernampattu",
      "Vellakoil",
      "Sivaganga",
      "Vadalur",
      "Rameshwaram",
      "Tiruvethipuram",
      "Perambalur",
      "Usilampatti",
      "Vedaranyam",
      "Sathyamangalam",
      "Puliyankudi",
      "Nanjikottai",
      "Thuraiyur",
      "Sirkali",
      "Tiruchendur",
      "Periyasemur",
      "Sattur",
      "Vandavasi",
      "Tharamangalam",
      "Tirukkoyilur",
      "Oddanchatram",
      "Palladam",
      "Vadakkuvalliyur",
      "Tirukalukundram",
      "Uthamapalayam",
      "Surandai",
      "Sankari",
      "Shenkottai",
      "Vadipatti",
      "Sholingur",
      "Tirupathur",
      "Manachanallur",
      "Viswanatham",
      "Polur",
      "Panagudi",
      "Uthiramerur",
      "Thiruthuraipoondi",
      "Pallapatti",
      "Ponneri",
      "Lalgudi",
      "Natham",
      "Unnamalaikadai",
      "P.N.Patti",
      "Tharangambadi",
      "Tittakudi",
      "Pacode",
      "O' Valley",
      "Suriyampalayam",
      "Sholavandan",
      "Thammampatti",
      "Namagiripettai",
      "Peravurani",
      "Parangipettai",
      "Pudupattinam",
      "Pallikonda",
      "Sivagiri",
      "Punjaipugalur",
      "Padmanabhapuram",
      "Thirupuvanam"
    ],
    "Madhya Pradesh": [
      "Indore",
      "Bhopal",
      "Jabalpur",
      "Gwalior",
      "Ujjain",
      "Sagar",
      "Ratlam",
      "Satna",
      "Murwara (Katni)",
      "Morena",
      "Singrauli",
      "Rewa",
      "Vidisha",
      "Ganjbasoda",
      "Shivpuri",
      "Mandsaur",
      "Neemuch",
      "Nagda",
      "Itarsi",
      "Sarni",
      "Sehore",
      "Mhow Cantonment",
      "Seoni",
      "Balaghat",
      "Ashok Nagar",
      "Tikamgarh",
      "Shahdol",
      "Pithampur",
      "Alirajpur",
      "Mandla",
      "Sheopur",
      "Shajapur",
      "Panna",
      "Raghogarh-Vijaypur",
      "Sendhwa",
      "Sidhi",
      "Pipariya",
      "Shujalpur",
      "Sironj",
      "Pandhurna",
      "Nowgong",
      "Mandideep",
      "Sihora",
      "Raisen",
      "Lahar",
      "Maihar",
      "Sanawad",
      "Sabalgarh",
      "Umaria",
      "Porsa",
      "Narsinghgarh",
      "Malaj Khand",
      "Sarangpur",
      "Mundi",
      "Nepanagar",
      "Pasan",
      "Mahidpur",
      "Seoni-Malwa",
      "Rehli",
      "Manawar",
      "Rahatgarh",
      "Panagar",
      "Wara Seoni",
      "Tarana",
      "Sausar",
      "Rajgarh",
      "Niwari",
      "Mauganj",
      "Manasa",
      "Nainpur",
      "Prithvipur",
      "Sohagpur",
      "Nowrozabad (Khodargama)",
      "Shamgarh",
      "Maharajpur",
      "Multai",
      "Pali",
      "Pachore",
      "Rau",
      "Mhowgaon",
      "Vijaypur",
      "Narsinghgarh"
    ],
    Jharkhand: [
      "Dhanbad",
      "Ranchi",
      "Jamshedpur",
      "Bokaro Steel City",
      "Deoghar",
      "Phusro",
      "Adityapur",
      "Hazaribag",
      "Giridih",
      "Ramgarh",
      "Jhumri Tilaiya",
      "Saunda",
      "Sahibganj",
      "Medininagar (Daltonganj)",
      "Chaibasa",
      "Chatra",
      "Gumia",
      "Dumka",
      "Madhupur",
      "Chirkunda",
      "Pakaur",
      "Simdega",
      "Musabani",
      "Mihijam",
      "Patratu",
      "Lohardaga",
      "Tenu dam-cum-Kathhara"
    ],
    Mizoram: [
      "Aizawl",
      "Lunglei",
      "Saiha"
    ],
    Nagaland: [
      "Dimapur",
      "Kohima",
      "Zunheboto",
      "Tuensang",
      "Wokha",
      "Mokokchung"
    ],
    "Himachal Pradesh": [
      "Shimla",
      "Mandi",
      "Solan",
      "Nahan",
      "Sundarnagar",
      "Palampur",
      "Kullu"
    ],
    Tripura: [
      "Agartala",
      "Udaipur",
      "Dharmanagar",
      "Pratapgarh",
      "Kailasahar",
      "Belonia",
      "Khowai"
    ],
    "Andhra Pradesh": [
      "Visakhapatnam",
      "Vijayawada",
      "Guntur",
      "Nellore",
      "Kurnool",
      "Rajahmundry",
      "Kakinada",
      "Tirupati",
      "Anantapur",
      "Kadapa",
      "Vizianagaram",
      "Eluru",
      "Ongole",
      "Nandyal",
      "Machilipatnam",
      "Adoni",
      "Tenali",
      "Chittoor",
      "Hindupur",
      "Proddatur",
      "Bhimavaram",
      "Madanapalle",
      "Guntakal",
      "Dharmavaram",
      "Gudivada",
      "Srikakulam",
      "Narasaraopet",
      "Rajampet",
      "Tadpatri",
      "Tadepalligudem",
      "Chilakaluripet",
      "Yemmiganur",
      "Kadiri",
      "Chirala",
      "Anakapalle",
      "Kavali",
      "Palacole",
      "Sullurpeta",
      "Tanuku",
      "Rayachoti",
      "Srikalahasti",
      "Bapatla",
      "Naidupet",
      "Nagari",
      "Gudur",
      "Vinukonda",
      "Narasapuram",
      "Nuzvid",
      "Markapur",
      "Ponnur",
      "Kandukur",
      "Bobbili",
      "Rayadurg",
      "Samalkot",
      "Jaggaiahpet",
      "Tuni",
      "Amalapuram",
      "Bheemunipatnam",
      "Venkatagiri",
      "Sattenapalle",
      "Pithapuram",
      "Palasa Kasibugga",
      "Parvathipuram",
      "Macherla",
      "Gooty",
      "Salur",
      "Mandapeta",
      "Jammalamadugu",
      "Peddapuram",
      "Punganur",
      "Nidadavole",
      "Repalle",
      "Ramachandrapuram",
      "Kovvur",
      "Tiruvuru",
      "Uravakonda",
      "Narsipatnam",
      "Yerraguntla",
      "Pedana",
      "Puttur",
      "Renigunta",
      "Rajam",
      "Srisailam Project (Right Flank Colony) Township"
    ],
    Punjab: [
      "Ludhiana",
      "Patiala",
      "Amritsar",
      "Jalandhar",
      "Bathinda",
      "Pathankot",
      "Hoshiarpur",
      "Batala",
      "Moga",
      "Malerkotla",
      "Khanna",
      "Mohali",
      "Barnala",
      "Firozpur",
      "Phagwara",
      "Kapurthala",
      "Zirakpur",
      "Kot Kapura",
      "Faridkot",
      "Muktsar",
      "Rajpura",
      "Sangrur",
      "Fazilka",
      "Gurdaspur",
      "Kharar",
      "Gobindgarh",
      "Mansa",
      "Malout",
      "Nabha",
      "Tarn Taran",
      "Jagraon",
      "Sunam",
      "Dhuri",
      "Firozpur Cantt.",
      "Sirhind Fatehgarh Sahib",
      "Rupnagar",
      "Jalandhar Cantt.",
      "Samana",
      "Nawanshahr",
      "Rampura Phul",
      "Nangal",
      "Nakodar",
      "Zira",
      "Patti",
      "Raikot",
      "Longowal",
      "Urmar Tanda",
      "Morinda, India",
      "Phillaur",
      "Pattran",
      "Qadian",
      "Sujanpur",
      "Mukerian",
      "Talwara"
    ],
    Chandigarh: [
      "Chandigarh"
    ],
    Rajasthan: [
      "Jaipur",
      "Jodhpur",
      "Bikaner",
      "Udaipur",
      "Ajmer",
      "Bhilwara",
      "Alwar",
      "Bharatpur",
      "Pali",
      "Barmer",
      "Sikar",
      "Tonk",
      "Sadulpur",
      "Sawai Madhopur",
      "Nagaur",
      "Makrana",
      "Sujangarh",
      "Sardarshahar",
      "Ladnu",
      "Ratangarh",
      "Nokha",
      "Nimbahera",
      "Suratgarh",
      "Rajsamand",
      "Lachhmangarh",
      "Rajgarh (Churu)",
      "Nasirabad",
      "Nohar",
      "Phalodi",
      "Nathdwara",
      "Pilani",
      "Merta City",
      "Sojat",
      "Neem-Ka-Thana",
      "Sirohi",
      "Pratapgarh",
      "Rawatbhata",
      "Sangaria",
      "Lalsot",
      "Pilibanga",
      "Pipar City",
      "Taranagar",
      "Vijainagar, Ajmer",
      "Sumerpur",
      "Sagwara",
      "Ramganj Mandi",
      "Lakheri",
      "Udaipurwati",
      "Losal",
      "Sri Madhopur",
      "Ramngarh",
      "Rawatsar",
      "Rajakhera",
      "Shahpura",
      "Shahpura",
      "Raisinghnagar",
      "Malpura",
      "Nadbai",
      "Sanchore",
      "Nagar",
      "Rajgarh (Alwar)",
      "Sheoganj",
      "Sadri",
      "Todaraisingh",
      "Todabhim",
      "Reengus",
      "Rajaldesar",
      "Sadulshahar",
      "Sambhar",
      "Prantij",
      "Mount Abu",
      "Mangrol",
      "Phulera",
      "Mandawa",
      "Pindwara",
      "Mandalgarh",
      "Takhatgarh"
    ],
    Assam: [
      "Guwahati",
      "Silchar",
      "Dibrugarh",
      "Nagaon",
      "Tinsukia",
      "Jorhat",
      "Bongaigaon City",
      "Dhubri",
      "Diphu",
      "North Lakhimpur",
      "Tezpur",
      "Karimganj",
      "Sibsagar",
      "Goalpara",
      "Barpeta",
      "Lanka",
      "Lumding",
      "Mankachar",
      "Nalbari",
      "Rangia",
      "Margherita",
      "Mangaldoi",
      "Silapathar",
      "Mariani",
      "Marigaon"
    ],
    Odisha: [
      "Bhubaneswar",
      "Cuttack",
      "Raurkela",
      "Brahmapur",
      "Sambalpur",
      "Puri",
      "Baleshwar Town",
      "Baripada Town",
      "Bhadrak",
      "Balangir",
      "Jharsuguda",
      "Bargarh",
      "Paradip",
      "Bhawanipatna",
      "Dhenkanal",
      "Barbil",
      "Kendujhar",
      "Sunabeda",
      "Rayagada",
      "Jatani",
      "Byasanagar",
      "Kendrapara",
      "Rajagangapur",
      "Parlakhemundi",
      "Talcher",
      "Sundargarh",
      "Phulabani",
      "Pattamundai",
      "Titlagarh",
      "Nabarangapur",
      "Soro",
      "Malkangiri",
      "Rairangpur",
      "Tarbha"
    ],
    Chhattisgarh: [
      "Raipur",
      "Bhilai Nagar",
      "Korba",
      "Bilaspur",
      "Durg",
      "Rajnandgaon",
      "Jagdalpur",
      "Raigarh",
      "Ambikapur",
      "Mahasamund",
      "Dhamtari",
      "Chirmiri",
      "Bhatapara",
      "Dalli-Rajhara",
      "Naila Janjgir",
      "Tilda Newra",
      "Mungeli",
      "Manendragarh",
      "Sakti"
    ],
    "Jammu and Kashmir": [
      "Srinagar",
      "Jammu",
      "Baramula",
      "Anantnag",
      "Sopore",
      "KathUrban Agglomeration",
      "Rajauri",
      "Punch",
      "Udhampur"
    ],
    Karnataka: [
      "Bengaluru",
      "Hubli-Dharwad",
      "Belagavi",
      "Mangaluru",
      "Davanagere",
      "Ballari",
      "Mysore",
      "Tumkur",
      "Shivamogga",
      "Raayachuru",
      "Robertson Pet",
      "Kolar",
      "Mandya",
      "Udupi",
      "Chikkamagaluru",
      "Karwar",
      "Ranebennuru",
      "Ranibennur",
      "Ramanagaram",
      "Gokak",
      "Yadgir",
      "Rabkavi Banhatti",
      "Shahabad",
      "Sirsi",
      "Sindhnur",
      "Tiptur",
      "Arsikere",
      "Nanjangud",
      "Sagara",
      "Sira",
      "Puttur",
      "Athni",
      "Mulbagal",
      "Surapura",
      "Siruguppa",
      "Mudhol",
      "Sidlaghatta",
      "Shahpur",
      "Saundatti-Yellamma",
      "Wadi",
      "Manvi",
      "Nelamangala",
      "Lakshmeshwar",
      "Ramdurg",
      "Nargund",
      "Tarikere",
      "Malavalli",
      "Savanur",
      "Lingsugur",
      "Vijayapura",
      "Sankeshwara",
      "Madikeri",
      "Talikota",
      "Sedam",
      "Shikaripur",
      "Mahalingapura",
      "Mudalagi",
      "Muddebihal",
      "Pavagada",
      "Malur",
      "Sindhagi",
      "Sanduru",
      "Afzalpur",
      "Maddur",
      "Madhugiri",
      "Tekkalakote",
      "Terdal",
      "Mudabidri",
      "Magadi",
      "Navalgund",
      "Shiggaon",
      "Shrirangapattana",
      "Sindagi",
      "Sakaleshapura",
      "Srinivaspur",
      "Ron",
      "Mundargi",
      "Sadalagi",
      "Piriyapatna",
      "Adyar"
    ],
    Manipur: [
      "Imphal",
      "Thoubal",
      "Lilong",
      "Mayang Imphal"
    ],
    Kerala: [
      "Thiruvananthapuram",
      "Kochi",
      "Kozhikode",
      "Kollam",
      "Thrissur",
      "Palakkad",
      "Alappuzha",
      "Malappuram",
      "Ponnani",
      "Vatakara",
      "Kanhangad",
      "Taliparamba",
      "Koyilandy",
      "Neyyattinkara",
      "Kayamkulam",
      "Nedumangad",
      "Kannur",
      "Tirur",
      "Kottayam",
      "Kasaragod",
      "Kunnamkulam",
      "Ottappalam",
      "Thiruvalla",
      "Thodupuzha",
      "Chalakudy",
      "Changanassery",
      "Punalur",
      "Nilambur",
      "Cherthala",
      "Perinthalmanna",
      "Mattannur",
      "Shoranur",
      "Varkala",
      "Paravoor",
      "Pathanamthitta",
      "Peringathur",
      "Attingal",
      "Kodungallur",
      "Pappinisseri",
      "Chittur-Thathamangalam",
      "Muvattupuzha",
      "Adoor",
      "Mavelikkara",
      "Mavoor",
      "Perumbavoor",
      "Vaikom",
      "Palai",
      "Panniyannur",
      "Guruvayoor",
      "Puthuppally",
      "Panamattom"
    ],
    Delhi: [
      "Delhi",
      "New Delhi"
    ],
    "Dadra and Nagar Haveli": [
      "Silvassa"
    ],
    Puducherry: [
      "Pondicherry",
      "Karaikal",
      "Yanam",
      "Mahe"
    ],
    Uttarakhand: [
      "Dehradun",
      "Hardwar",
      "Haldwani-cum-Kathgodam",
      "Srinagar",
      "Kashipur",
      "Roorkee",
      "Rudrapur",
      "Rishikesh",
      "Ramnagar",
      "Pithoragarh",
      "Manglaur",
      "Nainital",
      "Mussoorie",
      "Tehri",
      "Pauri",
      "Nagla",
      "Sitarganj",
      "Bageshwar"
    ],
    "Uttar Pradesh": [
      "Lucknow",
      "Kanpur",
      "Firozabad",
      "Agra",
      "Meerut",
      "Varanasi",
      "Allahabad",
      "Amroha",
      "Moradabad",
      "Aligarh",
      "Saharanpur",
      "Noida",
      "Loni",
      "Jhansi",
      "Shahjahanpur",
      "Rampur",
      "Modinagar",
      "Hapur",
      "Etawah",
      "Sambhal",
      "Orai",
      "Bahraich",
      "Unnao",
      "Rae Bareli",
      "Lakhimpur",
      "Sitapur",
      "Lalitpur",
      "Pilibhit",
      "Chandausi",
      "Hardoi ",
      "Azamgarh",
      "Khair",
      "Sultanpur",
      "Tanda",
      "Nagina",
      "Shamli",
      "Najibabad",
      "Shikohabad",
      "Sikandrabad",
      "Shahabad, Hardoi",
      "Pilkhuwa",
      "Renukoot",
      "Vrindavan",
      "Ujhani",
      "Laharpur",
      "Tilhar",
      "Sahaswan",
      "Rath",
      "Sherkot",
      "Kalpi",
      "Tundla",
      "Sandila",
      "Nanpara",
      "Sardhana",
      "Nehtaur",
      "Seohara",
      "Padrauna",
      "Mathura",
      "Thakurdwara",
      "Nawabganj",
      "Siana",
      "Noorpur",
      "Sikandra Rao",
      "Puranpur",
      "Rudauli",
      "Thana Bhawan",
      "Palia Kalan",
      "Zaidpur",
      "Nautanwa",
      "Zamania",
      "Shikarpur, Bulandshahr",
      "Naugawan Sadat",
      "Fatehpur Sikri",
      "Shahabad, Rampur",
      "Robertsganj",
      "Utraula",
      "Sadabad",
      "Rasra",
      "Lar",
      "Lal Gopalganj Nindaura",
      "Sirsaganj",
      "Pihani",
      "Shamsabad, Agra",
      "Rudrapur",
      "Soron",
      "SUrban Agglomerationr",
      "Samdhan",
      "Sahjanwa",
      "Rampur Maniharan",
      "Sumerpur",
      "Shahganj",
      "Tulsipur",
      "Tirwaganj",
      "PurqUrban Agglomerationzi",
      "Shamsabad, Farrukhabad",
      "Warhapur",
      "Powayan",
      "Sandi",
      "Achhnera",
      "Naraura",
      "Nakur",
      "Sahaspur",
      "Safipur",
      "Reoti",
      "Sikanderpur",
      "Saidpur",
      "Sirsi",
      "Purwa",
      "Parasi",
      "Lalganj",
      "Phulpur",
      "Shishgarh",
      "Sahawar",
      "Samthar",
      "Pukhrayan",
      "Obra",
      "Niwai",
      "Mirzapur"
    ],
    Bihar: [
      "Patna",
      "Gaya",
      "Bhagalpur",
      "Muzaffarpur",
      "Darbhanga",
      "Arrah",
      "Begusarai",
      "Chhapra",
      "Katihar",
      "Munger",
      "Purnia",
      "Saharsa",
      "Sasaram",
      "Hajipur",
      "Dehri-on-Sone",
      "Bettiah",
      "Motihari",
      "Bagaha",
      "Siwan",
      "Kishanganj",
      "Jamalpur",
      "Buxar",
      "Jehanabad",
      "Aurangabad",
      "Lakhisarai",
      "Nawada",
      "Jamui",
      "Sitamarhi",
      "Araria",
      "Gopalganj",
      "Madhubani",
      "Masaurhi",
      "Samastipur",
      "Mokameh",
      "Supaul",
      "Dumraon",
      "Arwal",
      "Forbesganj",
      "BhabUrban Agglomeration",
      "Narkatiaganj",
      "Naugachhia",
      "Madhepura",
      "Sheikhpura",
      "Sultanganj",
      "Raxaul Bazar",
      "Ramnagar",
      "Mahnar Bazar",
      "Warisaliganj",
      "Revelganj",
      "Rajgir",
      "Sonepur",
      "Sherghati",
      "Sugauli",
      "Makhdumpur",
      "Maner",
      "Rosera",
      "Nokha",
      "Piro",
      "Rafiganj",
      "Marhaura",
      "Mirganj",
      "Lalganj",
      "Murliganj",
      "Motipur",
      "Manihari",
      "Sheohar",
      "Maharajganj",
      "Silao",
      "Barh",
      "Asarganj"
    ],
    Gujarat: [
      "Ahmedabad",
      "Surat",
      "Vadodara",
      "Rajkot",
      "Bhavnagar",
      "Jamnagar",
      "Nadiad",
      "Porbandar",
      "Anand",
      "Morvi",
      "Mahesana",
      "Bharuch",
      "Vapi",
      "Navsari",
      "Veraval",
      "Bhuj",
      "Godhra",
      "Palanpur",
      "Valsad",
      "Patan",
      "Deesa",
      "Amreli",
      "Anjar",
      "Dhoraji",
      "Khambhat",
      "Mahuva",
      "Keshod",
      "Wadhwan",
      "Ankleshwar",
      "Savarkundla",
      "Kadi",
      "Visnagar",
      "Upleta",
      "Una",
      "Sidhpur",
      "Unjha",
      "Mangrol",
      "Viramgam",
      "Modasa",
      "Palitana",
      "Petlad",
      "Kapadvanj",
      "Sihor",
      "Wankaner",
      "Limbdi",
      "Mandvi",
      "Thangadh",
      "Vyara",
      "Padra",
      "Lunawada",
      "Rajpipla",
      "Vapi",
      "Umreth",
      "Sanand",
      "Rajula",
      "Radhanpur",
      "Mahemdabad",
      "Ranavav",
      "Tharad",
      "Mansa",
      "Umbergaon",
      "Talaja",
      "Vadnagar",
      "Manavadar",
      "Salaya",
      "Vijapur",
      "Pardi",
      "Rapar",
      "Songadh",
      "Lathi",
      "Adalaj",
      "Chhapra",
      "Gandhinagar"
    ],
    Telangana: [
      "Hyderabad",
      "Warangal",
      "Nizamabad",
      "Karimnagar",
      "Ramagundam",
      "Khammam",
      "Mahbubnagar",
      "Mancherial",
      "Adilabad",
      "Suryapet",
      "Jagtial",
      "Miryalaguda",
      "Nirmal",
      "Kamareddy",
      "Kothagudem",
      "Bodhan",
      "Palwancha",
      "Mandamarri",
      "Koratla",
      "Sircilla",
      "Tandur",
      "Siddipet",
      "Wanaparthy",
      "Kagaznagar",
      "Gadwal",
      "Sangareddy",
      "Bellampalle",
      "Bhongir",
      "Vikarabad",
      "Jangaon",
      "Bhadrachalam",
      "Bhainsa",
      "Farooqnagar",
      "Medak",
      "Narayanpet",
      "Sadasivpet",
      "Yellandu",
      "Manuguru",
      "Kyathampalle",
      "Nagarkurnool"
    ],
    Meghalaya: [
      "Shillong",
      "Tura",
      "Nongstoin"
    ],
    "Himachal Praddesh": [
      "Manali"
    ],
    "Arunachal Pradesh": [
      "Naharlagun",
      "Pasighat"
    ],
    Maharashtra: [
      "Mumbai",
      "Pune",
      "Nagpur",
      "Thane",
      "Nashik",
      "Kalyan-Dombivali",
      "Vasai-Virar",
      "Solapur",
      "Mira-Bhayandar",
      "Bhiwandi",
      "Amravati",
      "Nanded-Waghala",
      "Sangli",
      "Malegaon",
      "Akola",
      "Latur",
      "Dhule",
      "Ahmednagar",
      "Ichalkaranji",
      "Parbhani",
      "Panvel",
      "Yavatmal",
      "Achalpur",
      "Osmanabad",
      "Nandurbar",
      "Satara",
      "Wardha",
      "Udgir",
      "Aurangabad",
      "Amalner",
      "Akot",
      "Pandharpur",
      "Shrirampur",
      "Parli",
      "Washim",
      "Ambejogai",
      "Manmad",
      "Ratnagiri",
      "Uran Islampur",
      "Pusad",
      "Sangamner",
      "Shirpur-Warwade",
      "Malkapur",
      "Wani",
      "Lonavla",
      "Talegaon Dabhade",
      "Anjangaon",
      "Umred",
      "Palghar",
      "Shegaon",
      "Ozar",
      "Phaltan",
      "Yevla",
      "Shahade",
      "Vita",
      "Umarkhed",
      "Warora",
      "Pachora",
      "Tumsar",
      "Manjlegaon",
      "Sillod",
      "Arvi",
      "Nandura",
      "Vaijapur",
      "Wadgaon Road",
      "Sailu",
      "Murtijapur",
      "Tasgaon",
      "Mehkar",
      "Yawal",
      "Pulgaon",
      "Nilanga",
      "Wai",
      "Umarga",
      "Paithan",
      "Rahuri",
      "Nawapur",
      "Tuljapur",
      "Morshi",
      "Purna",
      "Satana",
      "Pathri",
      "Sinnar",
      "Uchgaon",
      "Uran",
      "Pen",
      "Karjat",
      "Manwath",
      "Partur",
      "Sangole",
      "Mangrulpir",
      "Risod",
      "Shirur",
      "Savner",
      "Sasvad",
      "Pandharkaoda",
      "Talode",
      "Shrigonda",
      "Shirdi",
      "Raver",
      "Mukhed",
      "Rajura",
      "Vadgaon Kasba",
      "Tirora",
      "Mahad",
      "Lonar",
      "Sawantwadi",
      "Pathardi",
      "Pauni",
      "Ramtek",
      "Mul",
      "Soyagaon",
      "Mangalvedhe",
      "Narkhed",
      "Shendurjana",
      "Patur",
      "Mhaswad",
      "Loha",
      "Nandgaon",
      "Warud"
    ],
    Goa: [
      "Marmagao",
      "Panaji",
      "Margao",
      "Mapusa"
    ],
    "West Bengal": [
      "Kolkata",
      "Siliguri",
      "Asansol",
      "Raghunathganj",
      "Kharagpur",
      "Naihati",
      "English Bazar",
      "Baharampur",
      "Hugli-Chinsurah",
      "Raiganj",
      "Jalpaiguri",
      "Santipur",
      "Balurghat",
      "Medinipur",
      "Habra",
      "Ranaghat",
      "Bankura",
      "Nabadwip",
      "Darjiling",
      "Purulia",
      "Arambagh",
      "Tamluk",
      "AlipurdUrban Agglomerationr",
      "Suri",
      "Jhargram",
      "Gangarampur",
      "Rampurhat",
      "Kalimpong",
      "Sainthia",
      "Taki",
      "Murshidabad",
      "Memari",
      "Paschim Punropara",
      "Tarakeswar",
      "Sonamukhi",
      "PandUrban Agglomeration",
      "Mainaguri",
      "Malda",
      "Panchla",
      "Raghunathpur",
      "Mathabhanga",
      "Monoharpur",
      "Srirampore",
      "Adra"
    ]
  };

  // state handling
  const [selectedState, setSelectedState] = useState("");
  const [cities, setCities] = useState([]);

  const handleStateChange = (stateName) => {
    setSelectedState(stateName);
    setCities(indiaData[stateName] || []);
  };
  // ---------- END STATES + CITIES DATA ----------

  const home = {
    hero: [
      {
        image: hero1,
        title: "Empowering Brighter Futures",
        desc: "Join Mother Teresa Educational Foundation in Ananthapuramu to achieve academic excellence and holistic development."
      },
      {
        image: hero2,
        title: "Innovate. Learn. Grow.",
        desc: "We provide quality education with modern facilities, expert faculty, and a student-centric approach."
      },
      {
        image: hero3,
        title: "Inspiring Lives, Shaping Careers",
        desc: "Discover endless opportunities and nurture your potential with our specialized programs and support."
      }
    ],

    courses: [
      {
        title: "Managment",
        list: ["PGMD", "MBA", "BBA", "BMS"],
        img: managment,
      },
      {
        title: "Managment",
        list: ["PGMD", "MBA", "BBA", "BMS"],
        img: engineering,
      },
      {
        title: "Managment",
        list: ["PGMD", "MBA", "BBA", "BMS"],
        img: medical,
      },
      {
        title: "Managment",
        list: ["PGMD", "MBA", "BBA", "BMS"],
        img: abroad,
      },
      {
        title: "Managment",
        list: ["PGMD", "MBA", "BBA", "BMS"],
        img: distance,
      },
    ],
    rankedInstitutes: [
      {
        img: auro,
        name: "Auro University",
        place: "Surat"
      },
      {
        img: iba,
        name: "Indus Business Academy (IBA)",
        place: "Bangalore"
      },
      {
        img: iicmt,
        name: "Institute of Industrial and Computer Management and Research",
        place: "Pune"
      },
      {
        img: jagsom,
        name: "Jagdish Sheth School of Management ( JAGSOM formerly known as IFIM Business School)",
        place: "Bangalore"
      },
      {
        img: isbr,
        name: "Institute of Industrial and Computer Management and Research",
        place: "Pune"
      },
      {
        img: ISBS,
        name: "Indira School of Business Studies",
        place: "Pune"
      },
      {
        img: itm,
        name: "ITM Navi Mumbai",
        place: "Mumbai"
      },
      {
        img: isbm,
        name: "International School of Business and Media",
        place: "Pune"
      },

      {
        img: gims,
        name: "GNIOT Institute of Management Studies (GIMS)",
        place: "Delhi & NCR"
      },
      {
        img: patil,
        name: "Dr. D.Y. Patil Vidyapeeth (GBSRC)",
        place: "Pune"
      },
      {
        img: nbs,
        name: "Narayana Business School (NBS)",
        place: "Ahmedabad"
      },
      {
        img: pgdm,
        name: "ITM Navi Mumbai",
        place: "Mumbai"
      },
      {
        img: pgdm2,
        name: "Indira School of Business Studies",
        place: "Pune"
      },
      {
        img: pgmd,
        name: "Dr. D.Y. Patil B-School Details",
        place: "Pune"
      },
      {
        img: rcm,
        name: "Regional College of Management (RCM) / (PGDM+ IBC)",
        place: "Bangalore"
      },
      {
        img: sbs,
        name: "Shanti Business School (SBS)",
        place: "Ahmedabad"
      }
    ],

    testimonials: [
      {
        img: at_1,
        name: "Anjali Reddy",
        review:
          "Mother Teresa Educational Foundation has transformed my learning experience in ways I never imagined. The faculty not only teaches but truly understands the challenges students face. They constantly encourage us to stay focused and believe in ourselves. The atmosphere here motivates me to aim higher every single day. From improving my study habits to helping me build confidence in communication, the foundation has played a major role in shaping who I am today. I genuinely feel supported, valued, and guided at every step."
      },
      {
        img: at_2,
        name: "Rakesh Kumar",
        review:
          "Joining the foundation has been one of the best decisions I’ve made for my educational journey. The individual attention we receive is something rare. Teachers ensure every concept is crystal clear, and they always push us to think critically and creatively. The doubt sessions, discussions, and regular feedback helped me improve consistently. Beyond academics, the mentors here help us build discipline, time management, and confidence. I feel prepared for my future because of the strong foundation they have given me."
      },
      {
        img: at_4,
        name: "Sowmya Devi",
        review:
          "Before joining the foundation, I was unsure about my strengths and career direction. But the environment here changed everything. The faculty helped me identify my abilities and guided me with patience and care. The classes are interactive, practical, and focused on real understanding rather than just memorizing. I love how the institution ensures students develop not only academically but also emotionally and socially. Today, I am more confident in my career choices and feel empowered to chase my goals thanks to their constant motivation."
      },
      {
        img: at_3,
        name: "Praveen Reddy",
        review:
          "What makes this foundation truly stand out is the dedication of the mentors. They always take extra time to explain things until everyone understands. Their mentorship helped me overcome my hesitation and communicate more confidently. The workshops, training sessions, and regular assessments gave me the discipline and clarity I needed. I can proudly say that the guidance I received here has prepared me well for future challenges, both academically and personally. It’s more than just an institution – it’s a family."
      },
      {
        img: at_6,
        name: "Neha Sharma",
        review:
          "The foundation provides a nurturing environment where students are encouraged to explore, express, and grow. Every day here has helped me improve in different ways—whether academically, creatively, or emotionally. The teachers not only educate but inspire and support us like guardians. I have become more confident, responsible, and self-driven because of their constant encouragement. I highly recommend this foundation to students who want quality education with genuine care and personal attention."
      },
      {
        img: at_5,
        name: "Vikram Singh",
        review:
          "What I appreciate most about the foundation is its holistic approach to education. It is not just about scoring marks; it’s about developing skills, confidence, and clarity. The career guidance sessions, interactive classes, and personalized mentorship have helped me become more focused and ambitious. The faculty is approachable, knowledgeable, and always ready to help, no matter how many doubts we ask. I feel much more confident about my abilities and future path because of the constant support and structured training provided here."
      }
    ]

  }
  const about = {
    counters: [
      { number: 10000, label: "Enrolled +" },
      { number: 100, label: "Colleges & Universities +" },
      { number: 50, label: "Courses +" },
      { number: 1000, label: "Counsellors +" },
    ],
  }
  const Links_Address = {
    socials: [
      { icon: BsInstagram, url: "https://instagram.com" },
      { icon: BsFacebook, url: "https://facebook.com" },
      { icon: BsLinkedin, url: "https://linkedin.com" },
      { icon: BsTwitter, url: "https://twitter.com" },
      { icon: BsYoutube, url: "https://youtube.com" }
    ],

    contact: [
      { icon: BsTelephoneFill, text: "+91 88857 727716" },
      { icon: BsEnvelopeFill, text: "support@yourdomain.com" },
      { icon: BsGeoAltFill, text: "Sri Skanda Residency, Dwaraka (Chalama Reddy), IOC Petrol Bunk Backside, Opp.Sri Chaitanya Junior Collage, Near RTC Bus Stan, Ananthapuramu - 515001, A.P." }
    ],

    map: {
      embedUrl: "https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d899.6066063852431!2d77.60121168303333!3d14.68651808772237!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e1!3m2!1sen!2sin!4v1764646362318!5m2!1sen!2sin"
    }

  }
  const Team = {
    teamData: [
      {
        img: auro,
        name: "Rahul Sharma",
        role: "Founder & CEO",
      },
      {
        img: auro,
        name: "Priya Nair",
        role: "Academic Head",
      },
      {
        img: auro,
        name: "Amit Verma",
        role: "Counsellor",
      },
      {
        img: auro,
        name: "Amit Verma",
        role: "Counsellor",
      }
    ]
  }
  const ourClients = {
    clients: [
      {
        img: auro,
        name: "Auro University",
        place: "Surat"
      },
      {
        img: auro,
        name: "Green Valley Institute of Technology",
        place: "Bengaluru, Karnataka"
      },
      {
        img: auro,
        name: "National Science & Research Academy",
        place: "Chennai, Tamil Nadu"
      },
      {
        img: auro,
        name: "Horizon Business School",
        place: "Pune, Maharashtra"
      },
      {
        img: auro,
        name: "Sunrise Engineering College",
        place: "Hyderabad, Telangana"
      },
      {
        img: auro,
        name: "Green Valley Institute of Technology",
        place: "Bengaluru, Karnataka"
      },
      {
        img: auro,
        name: "National Science & Research Academy",
        place: "Chennai, Tamil Nadu"
      },
      {
        img: auro,
        name: "Horizon Business School",
        place: "Pune, Maharashtra"
      },
      {
        img: auro,
        name: "Sunrise Engineering College",
        place: "Hyderabad, Telangana"
      },
      {
        img: auro,
        name: "Green Valley Institute of Technology",
        place: "Bengaluru, Karnataka"
      },
      {
        img: auro,
        name: "National Science & Research Academy",
        place: "Chennai, Tamil Nadu"
      },
      {
        img: auro,
        name: "Horizon Business School",
        place: "Pune, Maharashtra"
      },
      {
        img: auro,
        name: "Sunrise Engineering College",
        place: "Hyderabad, Telangana"
      },
      {
        img: auro,
        name: "Green Valley Institute of Technology",
        place: "Bengaluru, Karnataka"
      },
      {
        img: auro,
        name: "National Science & Research Academy",
        place: "Chennai, Tamil Nadu"
      },
      {
        img: auro,
        name: "Horizon Business School",
        place: "Pune, Maharashtra"
      }
    ]
  }
  return (
    <AppContext.Provider value={{
      logo, menus, Button, home, indiaData,
      selectedState,
      handleStateChange,
      cities, about, Team, ourClients, Links_Address, footer
    }}>
      {children}
    </AppContext.Provider>
  );
};

export const useApp = () => useContext(AppContext);
